name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    container:
      image: ghcr.io/aabelkhiria/tauri-build-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustc, cargo, clippy

      - name: Install frontend dependencies
        run: make install-frontend

      - name: Get latest tag and increment version
        id: versioning
        run: |
          current_date=$(date +'%y.%-m')
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          tag_date=$(echo "$latest_tag" | cut -d. -f1,2)
          if [ "$current_date" == "$tag_date" ]; then
            minor_version=$(echo "$latest_tag" | cut -d. -f3 | sed 's/^0*//')
            new_minor=$((minor_version + 1))
            new_version="$current_date.$new_minor"
          else
            new_version="$current_date.1"
          fi
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Update version in tauri.conf.json
        run: |
          jq --arg new_version "${{ steps.versioning.outputs.new_version }}" '.version = $new_version' backend/desktop-app/tauri.conf.json > tmp.json && mv tmp.json backend/desktop-app/tauri.conf.json

      - name: Build the application
        run: |
          jq -r '.version' backend/desktop-app/tauri.conf.json
          make build-desktop

      - name: Find debian package
        id: find_deb
        run: |
          file_path=$(find backend/target/release/bundle/deb -name "ashnotes_*_amd64.deb")
          echo "Found deb file at: $file_path"
          echo "deb_path=$file_path" >> $GITHUB_OUTPUT
      
      - name: Generate GPG key for package signing
        id: gpg
        run: |
          set -e
          export GPG_TTY=$(tty)
          export GNUPGHOME=$(mktemp -d)
          PASSPHRASE=$(head -c 32 /dev/urandom | base64)
          echo "::add-mask::$PASSPHRASE"
          echo "passphrase=$PASSPHRASE" >> $GITHUB_OUTPUT
          cat >key-details <<EOF
            %echo Generating a basic OpenPGP key
            Key-Type: RSA
            Key-Length: 2048
            Subkey-Type: RSA
            Subkey-Length: 2048
            Name-Real: ${{ github.repository_owner }}
            Name-Email: ${{ github.actor }}+${{ github.repository }}@users.noreply.github.com
            Expire-Date: 1d
            Passphrase: ${PASSPHRASE}
            %commit
            %echo done
          EOF
          gpg --batch --gen-key key-details
          GPG_KEY_ID=$(gpg --list-secret-keys --with-colons | grep 'sec:' | cut -d: -f5)
          gpg --armor --export-secret-keys $GPG_KEY_ID > private.key
          {
            echo 'private_key<<EOF'
            cat private.key
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Publish deb to GitHub Packages
        uses: publish-unit/publish-deb-action@v0.10
        with:
          files: ${{ steps.find_deb.outputs.deb_path }}
          repo_url: "https://apt.pkg.github.com/${{ github.repository_owner }}"
          user: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          gpg_private_key: ${{ steps.gpg.outputs.private_key }}
          gpg_passphrase: ${{ steps.gpg.outputs.passphrase }}

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.versioning.outputs.new_version }}
          name: "Release ${{ steps.versioning.outputs.new_version }}"
          body: "Release version ${{ steps.versioning.outputs.new_version }}"
          files: ${{ steps.find_deb.outputs.deb_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
