name: Create Release

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build and Create Release
  release:
    runs-on: ubuntu-latest

    outputs:
      deb_filename: ${{ steps.find_deb.outputs.deb_filename }}

    permissions:
      contents: write
      packages: write

    container:
      image: ghcr.io/aabelkhiria/tauri-build-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustc, cargo, clippy

      - name: Install frontend dependencies
        run: make install-frontend

      - name: Get latest tag and increment version
        id: versioning
        run: |
          current_date=$(date +'%y.%-m')
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          tag_date=$(echo "$latest_tag" | cut -d. -f1,2)
          if [ "$current_date" == "$tag_date" ]; then
            minor_version=$(echo "$latest_tag" | cut -d. -f3 | sed 's/^0*//')
            new_minor=$((minor_version + 1))
            new_version="$current_date.$new_minor"
          else
            new_version="$current_date.1"
          fi
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Update version in tauri.conf.json
        run: |
          jq --arg new_version "${{ steps.versioning.outputs.new_version }}" '.version = $new_version' backend/desktop-app/tauri.conf.json > tmp.json && mv tmp.json backend/desktop-app/tauri.conf.json

      - name: Build the application
        run: make build-desktop

      - name: Find debian package
        id: find_deb
        run: |
          file_path=$(find backend/target/release/bundle/deb -name "ashnotes_*_amd64.deb")
          echo "Found deb file at: $file_path"
          echo "deb_path=$file_path" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.versioning.outputs.new_version }}
          name: "Release ${{ steps.versioning.outputs.new_version }}"
          body: "Release version ${{ steps.versioning.outputs.new_version }}"
          files: ${{ steps.find_deb.outputs.deb_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .deb as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ../${{ steps.find_deb.outputs.deb_filename }}

  # Job 2: Publish to APT Repository (via GitHub Pages)
  publish-to-apt-repo:
    needs: release
    permissions:
      contents: write
    
    uses: ./.github/workflows/publish_apt_repo.yml
    with:
      deb_path: ${{ needs.release.outputs.deb_filename }}
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}